In [8]:
import numpy as np

a = np.arange(15)
print(a)

a = a.reshape(3, 5)
print(a)

print(f'a.shape = {a.shape}')
print(f'a.size = {a.size}')
print(f'a.ndim = {a.ndim}')
print(f'a.dtype.name = {a.dtype.name}')
print(f'a.itemsize = {a.itemsize}')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape = (3, 5)
a.ndim = 2
a.dtype.name = int64
a.itemsize = 8
a.size = 15
